project:
  type: website
  output-dir: docs

website:
  title: "Jiyung-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JiYung531/Jiyung-blog
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



